version: '3.8'

services:
  be-auth-service:
    build:
      context: .
      dockerfile: apps/be-auth-service/Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=development
    restart: unless-stopped
